FROM node:10.16.0-stretch-slim

ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV

ARG PORT=4001
ENV PORT $PORT
EXPOSE 4001

RUN mkdir -p /opt/node_app && chown -R node:node /opt/node_app
WORKDIR /opt/node_app

# the official node image provides an unprivileged user as a security best practice
# but we have to manually enable it. We put it here so npm installs dependencies as the same
# user who runs the app. 
# https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#non-root-user
USER node
COPY package*.json ./
RUN npm install && npm cache clean --force
ENV PATH /opt/node_app/node_modules/.bin:$PATH

# copy in our source code last, as it changes the most
COPY --chown=node:node . .

CMD [ "npm", "run", "dev" ]